name: tests
on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Run tests
        run: |
          go test ./...
